# 相机配置
camera:
  name: "Hadron 640R EO"
  resolution:
    width: 1280
    height: 720
  
  # 相机内参矩阵
  intrinsics:
    fx: 932.82977
    fy: 926.87051
    cx: 612.40039
    cy: 356.25877

# GStreamer 配置
gstreamer:
  udp_port: 5005
  buffer_size: 2097152
  latency: 200
  encoding: "H265"
  max_buffers: 1
  drop: true

